### ISSUE TITLE
Allow comments in lists

### ISSUE THREAD

**Issue by arv** [domenic/ecmarkdown#21]
I had the following md:

```md
1. abc
  <!-- comment -->
  1. def
```

And I get the error message:

```
Possibly unhandled SyntaxError. Expected "  " or [0-9] but "<" found.
```

**Comment by bterlson** [comment]
I could probably parse this out on my end before passing to emd but emd also does not like blank lines:

```
1. a

2. b
```

will fail. Probably by design, too. So I could be smarter and remove whitespace around comments too but that seems prone to failure and more difficult than simply handling html comments in the emd grammar (which, afaict, shouldn't be too difficult).

**Comment by domenic** [comment]
Yep, agreed this should be handled by EMD.

We could also allow dedicated comment syntax, e.g. `//`.

**Comment by bterlson** [comment]
I think we need to support html comments at a minimum. I'm not opposed to a comment shorthand but I'm not sure it's necessary either :)
